"""
Build driver for metatensor-jax. Mirrors python/metatensor_torch/setup.py:
cmake_ext drives the metatensor-jax/CMakeLists.txt build, installs
``libmetatensor_jax.{so,dylib,dll}`` next to the python package, and the
loader in ``_c_lib.py`` picks it up at import time.
"""

from __future__ import annotations

import os
import subprocess
import sys

from setuptools import Extension, setup
from setuptools.command.bdist_wheel import bdist_wheel
from setuptools.command.build_ext import build_ext


ROOT = os.path.realpath(os.path.dirname(__file__))
METATENSOR_CORE_SRC = os.path.realpath(os.path.join(ROOT, "..", "metatensor_core"))
METATENSOR_JAX_SRC = os.path.realpath(os.path.join(ROOT, "..", "..", "metatensor-jax"))

METATENSOR_BUILD_TYPE = os.environ.get("METATENSOR_BUILD_TYPE", "release")
if METATENSOR_BUILD_TYPE not in ("debug", "release"):
    raise SystemExit(
        f"invalid METATENSOR_BUILD_TYPE: {METATENSOR_BUILD_TYPE!r}, "
        "expected 'debug' or 'release'"
    )


class universal_wheel(bdist_wheel):
    """Mark the wheel as compatible with any Python >=3 even though it ships
    a binary extension. Mirrors the metatensor-torch trick."""

    def get_tag(self):
        tag = bdist_wheel.get_tag(self)
        return ("py3", "none") + tag[2:]


class cmake_ext(build_ext):
    """Build libmetatensor_jax.so via metatensor-jax/CMakeLists.txt."""

    def run(self):
        import metatensor

        source_dir = METATENSOR_JAX_SRC
        build_dir = os.path.join(ROOT, "build", "cmake-build")
        install_dir = os.path.join(
            os.path.realpath(self.build_lib), "metatensor_jax"
        )
        os.makedirs(build_dir, exist_ok=True)

        # XLA FFI headers ship with jaxlib; the include path is exported by
        # /etc/profile.d/metatensor-jax.sh. Fall back to introspecting jaxlib
        # if the env var is not set, so a plain `pip install .` works.
        xla_include = os.environ.get("XLA_FFI_INCLUDE_DIR")
        if not xla_include:
            try:
                import jaxlib
                xla_include = os.path.join(
                    os.path.dirname(jaxlib.__file__), "include"
                )
            except ImportError as exc:
                raise RuntimeError(
                    "metatensor-jax needs the XLA FFI headers from jaxlib. "
                    "Install jaxlib first, or set XLA_FFI_INCLUDE_DIR."
                ) from exc

        cmake_prefix_path = [metatensor.utils.cmake_prefix_path]
        cmake_options = [
            "-DCMAKE_VERBOSE_MAKEFILE=ON",
            f"-DCMAKE_BUILD_TYPE={METATENSOR_BUILD_TYPE}",
            f"-DCMAKE_INSTALL_PREFIX={install_dir}",
            "-DCMAKE_INSTALL_LIBDIR=lib",
            f"-DCMAKE_PREFIX_PATH={';'.join(cmake_prefix_path)}",
            f"-DXLA_FFI_INCLUDE_DIR={xla_include}",
        ]

        subprocess.run(
            ["cmake", source_dir, *cmake_options],
            cwd=build_dir,
            check=True,
        )
        subprocess.run(
            [
                "cmake",
                "--build", build_dir,
                "--parallel",
                "--config", "Release",
                "--target", "install",
            ],
            check=True,
        )

        with open(os.path.join(install_dir, "_build_versions.py"), "w") as fd:
            fd.write("# Autogenerated file, do not edit\n\n")
            fd.write(
                f"BUILD_METATENSOR_CORE_VERSION = '{metatensor.__version__}'\n"
            )


if __name__ == "__main__":
    setup(
        ext_modules=[
            Extension(name="metatensor_jax", sources=[]),
        ],
        cmdclass={
            "build_ext": cmake_ext,
            "bdist_wheel": universal_wheel,
        },
        package_data={
            "metatensor_jax": [
                "lib/*",
                "*.so",
                "*.dylib",
                "*.dll",
                "_build_versions.py",
            ]
        },
    )
