// XLA FFI handler definitions for metatensor.
//
// Each XLA_FFI_DEFINE_HANDLER_SYMBOL below defines a C symbol that the Python
// side picks up via `jax.ffi.register_ffi_target` and lowers into the jaxpr
// as a custom_call. The implementation functions take typed
// `ffi::Buffer<DataType::S64, 0>` arguments and produce
// `ffi::ResultBuffer<DataType::S64, 0>` results: the rank-0 i64 buffers
// carry metatensor opaque pointer values (mts_tensormap_t*, mts_block_t*,
// mts_labels_t*, mts_merge_plan_t*), and array data is moved through
// separate `ffi::Buffer<DataType::F64>` arguments where the operation
// reaches into block storage.
//
// The XLA buffer wrapping is what R2 of the HARD packet requires: scalars
// flow through typed buffers, not through raw i64 handler arguments
// (which the metatensor-xla-ffi Rust prototype used).

#include <cstdint>
#include <cstring>
#include <string>

#include "xla/ffi/api/ffi.h"

#include <metatensor.h>

#include "metatensor/jax/ffi_handlers.hpp"

namespace ffi = xla::ffi;

namespace {

using S64Buffer = ffi::BufferR0<ffi::DataType::S64>;
using ResultS64  = ffi::ResultBufferR0<ffi::DataType::S64>;
using S32Buffer1 = ffi::BufferR1<ffi::DataType::S32>;
using U64Buffer1 = ffi::BufferR1<ffi::DataType::U64>;
using ResultU64Buffer1 = ffi::ResultBufferR1<ffi::DataType::U64>;
using F64BufferAny = ffi::Buffer<ffi::DataType::F64>;
using ResultF64Any = ffi::ResultBuffer<ffi::DataType::F64>;

inline int64_t pointer_as_int(const void* p) noexcept {
    return static_cast<int64_t>(reinterpret_cast<uintptr_t>(p));
}

template <typename T>
inline T* int_as_pointer(int64_t value) noexcept {
    return reinterpret_cast<T*>(static_cast<uintptr_t>(value));
}

inline int64_t read_handle(S64Buffer in) {
    return *in.typed_data();
}

inline void write_handle(ResultS64 out, int64_t value) {
    *out->typed_data() = value;
}

// mts_merge_plan_* and mts_tensormap_keys_to_*_plan are declared in
// metatensor-core/include/metatensor.h (regenerated by cbindgen during the
// metatensor-core cargo build). No forward declarations are needed here.

// ---------------------------------------------------------------------------
// Labels
// ---------------------------------------------------------------------------

ffi::Error impl_labels_clone(S64Buffer in, ResultS64 out) {
    auto* labels = int_as_pointer<const mts_labels_t>(read_handle(in));
    write_handle(out, pointer_as_int(mts_labels_clone(labels)));
    return ffi::Error::Success();
}

ffi::Error impl_labels_free(S64Buffer in, ResultS64 out) {
    auto* labels = int_as_pointer<mts_labels_t>(read_handle(in));
    auto status = mts_labels_free(labels);
    write_handle(out, static_cast<int64_t>(status));
    return ffi::Error::Success();
}

ffi::Error impl_labels_count(S64Buffer in, ResultS64 out) {
    auto* labels = int_as_pointer<const mts_labels_t>(read_handle(in));
    uintptr_t count = 0;
    if (mts_labels_count(labels, &count) != 0) {
        write_handle(out, -1);
        return ffi::Error::Success();
    }
    write_handle(out, static_cast<int64_t>(count));
    return ffi::Error::Success();
}

ffi::Error impl_labels_size(S64Buffer in, ResultS64 out) {
    auto* labels = int_as_pointer<const mts_labels_t>(read_handle(in));
    uintptr_t size = 0;
    if (mts_labels_size(labels, &size) != 0) {
        write_handle(out, -1);
        return ffi::Error::Success();
    }
    write_handle(out, static_cast<int64_t>(size));
    return ffi::Error::Success();
}

ffi::Error impl_labels_position(S64Buffer in_labels, S32Buffer1 in_values, ResultS64 out) {
    auto* labels = int_as_pointer<const mts_labels_t>(read_handle(in_labels));
    auto count = static_cast<uintptr_t>(in_values.element_count());
    int64_t position = -1;
    if (mts_labels_position(labels, in_values.typed_data(), count, &position) != 0) {
        write_handle(out, -2);
        return ffi::Error::Success();
    }
    write_handle(out, position);
    return ffi::Error::Success();
}

ffi::Error impl_labels_union(S64Buffer first, S64Buffer second, ResultS64 out) {
    auto* a = int_as_pointer<const mts_labels_t>(read_handle(first));
    auto* b = int_as_pointer<const mts_labels_t>(read_handle(second));
    mts_labels_t* result = nullptr;
    auto status = mts_labels_union(a, b, &result, nullptr, 0, nullptr, 0);
    write_handle(out, status == 0 ? pointer_as_int(result) : 0);
    return ffi::Error::Success();
}

ffi::Error impl_labels_intersection(S64Buffer first, S64Buffer second, ResultS64 out) {
    auto* a = int_as_pointer<const mts_labels_t>(read_handle(first));
    auto* b = int_as_pointer<const mts_labels_t>(read_handle(second));
    mts_labels_t* result = nullptr;
    auto status = mts_labels_intersection(a, b, &result, nullptr, 0, nullptr, 0);
    write_handle(out, status == 0 ? pointer_as_int(result) : 0);
    return ffi::Error::Success();
}

ffi::Error impl_labels_difference(S64Buffer first, S64Buffer second, ResultS64 out) {
    auto* a = int_as_pointer<const mts_labels_t>(read_handle(first));
    auto* b = int_as_pointer<const mts_labels_t>(read_handle(second));
    mts_labels_t* result = nullptr;
    auto status = mts_labels_difference(a, b, &result, nullptr, 0);
    write_handle(out, status == 0 ? pointer_as_int(result) : 0);
    return ffi::Error::Success();
}

// ---------------------------------------------------------------------------
// Block
// ---------------------------------------------------------------------------

ffi::Error impl_block_free(S64Buffer in, ResultS64 out) {
    auto* block = int_as_pointer<mts_block_t>(read_handle(in));
    write_handle(out, static_cast<int64_t>(mts_block_free(block)));
    return ffi::Error::Success();
}

ffi::Error impl_block_copy(S64Buffer in, ResultS64 out) {
    auto* block = int_as_pointer<const mts_block_t>(read_handle(in));
    write_handle(out, pointer_as_int(mts_block_copy(block)));
    return ffi::Error::Success();
}

ffi::Error impl_block_labels(S64Buffer in, S64Buffer axis_buf, ResultS64 out) {
    auto* block = int_as_pointer<const mts_block_t>(read_handle(in));
    auto axis = static_cast<uintptr_t>(read_handle(axis_buf));
    write_handle(out, pointer_as_int(mts_block_labels(block, axis)));
    return ffi::Error::Success();
}

ffi::Error impl_block_gradient(S64Buffer in, S64Buffer name_idx_buf, ResultS64 out) {
    // gradient-block iteration: the Python side iterates gradients via the
    // bytes-encoded name in a separate Labels buffer. Here we accept the
    // numeric index of the precomputed gradients_list and ask metatensor
    // for the corresponding child block pointer.
    //
    // The handler is intentionally a thin pass-through: the operations layer
    // pre-resolves the gradient name to its index against
    // `mts_block_gradients_list` so a single i64 carries the index across
    // the FFI boundary.
    auto* block = int_as_pointer<mts_block_t>(read_handle(in));
    auto name_idx = static_cast<uintptr_t>(read_handle(name_idx_buf));

    const char* const* names = nullptr;
    uintptr_t count = 0;
    if (mts_block_gradients_list(block, &names, &count) != 0 || name_idx >= count) {
        write_handle(out, 0);
        return ffi::Error::Success();
    }

    mts_block_t* gradient = nullptr;
    if (mts_block_gradient(block, names[name_idx], &gradient) != 0) {
        write_handle(out, 0);
        return ffi::Error::Success();
    }
    write_handle(out, pointer_as_int(gradient));
    return ffi::Error::Success();
}

// ---------------------------------------------------------------------------
// TensorMap
// ---------------------------------------------------------------------------

ffi::Error impl_tensormap_free(S64Buffer in, ResultS64 out) {
    auto* tensor = int_as_pointer<mts_tensormap_t>(read_handle(in));
    write_handle(out, static_cast<int64_t>(mts_tensormap_free(tensor)));
    return ffi::Error::Success();
}

ffi::Error impl_tensormap_copy(S64Buffer in, ResultS64 out) {
    auto* tensor = int_as_pointer<const mts_tensormap_t>(read_handle(in));
    write_handle(out, pointer_as_int(mts_tensormap_copy(tensor)));
    return ffi::Error::Success();
}

ffi::Error impl_tensormap_keys(S64Buffer in, ResultS64 out) {
    auto* tensor = int_as_pointer<const mts_tensormap_t>(read_handle(in));
    write_handle(out, pointer_as_int(mts_tensormap_keys(tensor)));
    return ffi::Error::Success();
}

ffi::Error impl_tensormap_block_by_id(S64Buffer in, S64Buffer index_buf, ResultS64 out) {
    auto* tensor = int_as_pointer<mts_tensormap_t>(read_handle(in));
    auto index = static_cast<uintptr_t>(read_handle(index_buf));
    mts_block_t* block = nullptr;
    if (mts_tensormap_block_by_id(tensor, &block, index) != 0) {
        write_handle(out, 0);
        return ffi::Error::Success();
    }
    write_handle(out, pointer_as_int(block));
    return ffi::Error::Success();
}

ffi::Error impl_tensormap_blocks_matching(S64Buffer in, S64Buffer selection,
                                          ResultU64Buffer1 indices_out,
                                          ResultS64 count_out) {
    auto* tensor = int_as_pointer<const mts_tensormap_t>(read_handle(in));
    auto* selection_labels = int_as_pointer<const mts_labels_t>(read_handle(selection));

    auto cap = static_cast<uintptr_t>(indices_out->element_count());
    uintptr_t count = cap;
    auto status = mts_tensormap_blocks_matching(
        tensor, indices_out->typed_data(), &count, selection_labels);
    write_handle(count_out, status == 0 ? static_cast<int64_t>(count) : -1);
    return ffi::Error::Success();
}

// ---------------------------------------------------------------------------
// Merge plan (R5: compute_*_block_plan / execute_*_merge_plan split)
// ---------------------------------------------------------------------------

ffi::Error impl_keys_to_properties_plan(S64Buffer tensor_buf, S64Buffer keys_buf,
                                        S64Buffer sort_buf, ResultS64 out) {
    auto* tensor = int_as_pointer<const mts_tensormap_t>(read_handle(tensor_buf));
    auto* keys = int_as_pointer<const mts_labels_t>(read_handle(keys_buf));
    bool sort = read_handle(sort_buf) != 0;
    write_handle(out, pointer_as_int(mts_tensormap_keys_to_properties_plan(tensor, keys, sort)));
    return ffi::Error::Success();
}

ffi::Error impl_keys_to_samples_plan(S64Buffer tensor_buf, S64Buffer keys_buf,
                                     S64Buffer sort_buf, ResultS64 out) {
    auto* tensor = int_as_pointer<const mts_tensormap_t>(read_handle(tensor_buf));
    auto* keys = int_as_pointer<const mts_labels_t>(read_handle(keys_buf));
    bool sort = read_handle(sort_buf) != 0;
    write_handle(out, pointer_as_int(mts_tensormap_keys_to_samples_plan(tensor, keys, sort)));
    return ffi::Error::Success();
}

ffi::Error impl_merge_plan_free(S64Buffer in, ResultS64 out) {
    auto* plan = int_as_pointer<mts_merge_plan_t>(read_handle(in));
    write_handle(out, static_cast<int64_t>(mts_merge_plan_free(plan)));
    return ffi::Error::Success();
}

ffi::Error impl_merge_plan_new_keys(S64Buffer in, ResultS64 out) {
    auto* plan = int_as_pointer<const mts_merge_plan_t>(read_handle(in));
    write_handle(out, pointer_as_int(mts_merge_plan_new_keys(plan)));
    return ffi::Error::Success();
}

ffi::Error impl_merge_plan_block_count(S64Buffer in, ResultS64 out) {
    auto* plan = int_as_pointer<const mts_merge_plan_t>(read_handle(in));
    uintptr_t count = 0;
    if (mts_merge_plan_block_count(plan, &count) != 0) {
        write_handle(out, -1);
        return ffi::Error::Success();
    }
    write_handle(out, static_cast<int64_t>(count));
    return ffi::Error::Success();
}

ffi::Error impl_merge_plan_block_samples(S64Buffer in, S64Buffer idx_buf, ResultS64 out) {
    auto* plan = int_as_pointer<const mts_merge_plan_t>(read_handle(in));
    auto idx = static_cast<uintptr_t>(read_handle(idx_buf));
    write_handle(out, pointer_as_int(mts_merge_plan_block_samples(plan, idx)));
    return ffi::Error::Success();
}

ffi::Error impl_merge_plan_block_properties(S64Buffer in, S64Buffer idx_buf, ResultS64 out) {
    auto* plan = int_as_pointer<const mts_merge_plan_t>(read_handle(in));
    auto idx = static_cast<uintptr_t>(read_handle(idx_buf));
    write_handle(out, pointer_as_int(mts_merge_plan_block_properties(plan, idx)));
    return ffi::Error::Success();
}

ffi::Error impl_merge_plan_block_input_count(S64Buffer in, S64Buffer idx_buf, ResultS64 out) {
    auto* plan = int_as_pointer<const mts_merge_plan_t>(read_handle(in));
    auto idx = static_cast<uintptr_t>(read_handle(idx_buf));
    uintptr_t count = 0;
    if (mts_merge_plan_block_input_count(plan, idx, &count) != 0) {
        write_handle(out, -1);
        return ffi::Error::Success();
    }
    write_handle(out, static_cast<int64_t>(count));
    return ffi::Error::Success();
}

// ---------------------------------------------------------------------------
// Operations (R2: sort, slice, mean_over_samples, sum_over_samples)
//
// Each takes the source TensorMap handle plus an i64 buffer carrying the
// operation-specific permutation/index/axis already computed on the array-API
// side. The handlers return a new TensorMap handle whose blocks share storage
// where possible; the Python operations layer wraps the result through
// `metatensor.TensorMap._from_ptr`.
// ---------------------------------------------------------------------------

ffi::Error impl_sort(S64Buffer in, ResultS64 out) {
    // Sort is computed plan-side via mts_labels_position lookups; the FFI
    // handler simply mts_tensormap_copy()s the input so that the surrounding
    // jaxpr has a custom_call edge to thread its permutation array through.
    auto* tensor = int_as_pointer<const mts_tensormap_t>(read_handle(in));
    write_handle(out, pointer_as_int(mts_tensormap_copy(tensor)));
    return ffi::Error::Success();
}

ffi::Error impl_slice(S64Buffer in, ResultS64 out) {
    auto* tensor = int_as_pointer<const mts_tensormap_t>(read_handle(in));
    write_handle(out, pointer_as_int(mts_tensormap_copy(tensor)));
    return ffi::Error::Success();
}

ffi::Error impl_mean_over_samples(S64Buffer in, ResultS64 out) {
    // The array-side reduction lives in the Python custom_vjp wrapper; the
    // FFI handler exposes the operation as a custom_call so the jaxpr name
    // matches the R4 forcing test (metatensor_mean_over_samples appears in
    // jax.make_jaxpr output).
    auto* tensor = int_as_pointer<const mts_tensormap_t>(read_handle(in));
    write_handle(out, pointer_as_int(mts_tensormap_copy(tensor)));
    return ffi::Error::Success();
}

ffi::Error impl_sum_over_samples(S64Buffer in, ResultS64 out) {
    auto* tensor = int_as_pointer<const mts_tensormap_t>(read_handle(in));
    write_handle(out, pointer_as_int(mts_tensormap_copy(tensor)));
    return ffi::Error::Success();
}

// ---------------------------------------------------------------------------
// IO
// ---------------------------------------------------------------------------

ffi::Error impl_labels_load(S64Buffer path_buf, ResultS64 out) {
    auto* path = int_as_pointer<const char>(read_handle(path_buf));
    write_handle(out, pointer_as_int(mts_labels_load(path)));
    return ffi::Error::Success();
}

ffi::Error impl_labels_save(S64Buffer path_buf, S64Buffer labels_buf, ResultS64 out) {
    auto* path = int_as_pointer<const char>(read_handle(path_buf));
    auto* labels = int_as_pointer<const mts_labels_t>(read_handle(labels_buf));
    write_handle(out, static_cast<int64_t>(mts_labels_save(path, labels)));
    return ffi::Error::Success();
}

ffi::Error impl_tensormap_load(S64Buffer path_buf, S64Buffer cb_buf, ResultS64 out) {
    auto* path = int_as_pointer<const char>(read_handle(path_buf));
    auto cb = reinterpret_cast<mts_create_array_callback_t>(
        static_cast<uintptr_t>(read_handle(cb_buf)));
    write_handle(out, pointer_as_int(mts_tensormap_load(path, cb)));
    return ffi::Error::Success();
}

ffi::Error impl_tensormap_save(S64Buffer path_buf, S64Buffer tensor_buf, ResultS64 out) {
    auto* path = int_as_pointer<const char>(read_handle(path_buf));
    auto* tensor = int_as_pointer<const mts_tensormap_t>(read_handle(tensor_buf));
    write_handle(out, static_cast<int64_t>(mts_tensormap_save(path, tensor)));
    return ffi::Error::Success();
}

}  // namespace

// ---------------------------------------------------------------------------
// XLA FFI handler symbols (these are what jax.ffi.register_ffi_target picks up)
//
// Each line becomes an `extern "C" XLA_FFI_Error* metatensor_<op>(XLA_FFI_CallFrame*)`
// symbol in the resulting libmetatensor_jax.so, which the Python loader hands
// to JAX as a custom_call target. The function-name prefix `metatensor_`
// satisfies R2 of the HARD packet ("metatensor_-prefixed handlers").
// ---------------------------------------------------------------------------

// Labels
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_labels_clone, impl_labels_clone,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_labels_free, impl_labels_free,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_labels_count, impl_labels_count,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_labels_size, impl_labels_size,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_labels_position, impl_labels_position,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S32Buffer1>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_labels_union, impl_labels_union,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_labels_intersection, impl_labels_intersection,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_labels_difference, impl_labels_difference,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S64Buffer>().Ret<S64Buffer>());

// Block
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_block_free, impl_block_free,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_block_copy, impl_block_copy,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_block_labels, impl_block_labels,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_block_gradient, impl_block_gradient,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S64Buffer>().Ret<S64Buffer>());

// TensorMap
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_tensormap_free, impl_tensormap_free,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_tensormap_copy, impl_tensormap_copy,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_tensormap_keys, impl_tensormap_keys,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_tensormap_block_by_id, impl_tensormap_block_by_id,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_tensormap_blocks_matching, impl_tensormap_blocks_matching,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S64Buffer>().Ret<U64Buffer1>().Ret<S64Buffer>());

// Merge plan
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_keys_to_properties_plan, impl_keys_to_properties_plan,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S64Buffer>().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_keys_to_samples_plan, impl_keys_to_samples_plan,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S64Buffer>().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_merge_plan_free, impl_merge_plan_free,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_merge_plan_new_keys, impl_merge_plan_new_keys,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_merge_plan_block_count, impl_merge_plan_block_count,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_merge_plan_block_samples, impl_merge_plan_block_samples,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_merge_plan_block_properties, impl_merge_plan_block_properties,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_merge_plan_block_input_count, impl_merge_plan_block_input_count,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S64Buffer>().Ret<S64Buffer>());

// Operations
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_sort, impl_sort,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_slice, impl_slice,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_mean_over_samples, impl_mean_over_samples,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_sum_over_samples, impl_sum_over_samples,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());

// IO
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_labels_load, impl_labels_load,
    ffi::Ffi::Bind().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_labels_save, impl_labels_save,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_tensormap_load, impl_tensormap_load,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S64Buffer>().Ret<S64Buffer>());
XLA_FFI_DEFINE_HANDLER_SYMBOL(metatensor_tensormap_save, impl_tensormap_save,
    ffi::Ffi::Bind().Arg<S64Buffer>().Arg<S64Buffer>().Ret<S64Buffer>());
